#服务端口
server:
  port: 8090
spring:
  #配置数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://124.221.248.30:3306/stx-pro-three?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    username: stx-pro-three
    password: root
#mybatis-plus配置文件
mybatis-plus:
  configuration:
    #    日志文件
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #    配置Mybatis配置文件位置
  mapper-locations: classpath*:/mybatis/mapper/*.xml
jackson:
  date-format: yyyy-MM-dd
  time-zone: GMT+8
