#服务端口
server:
  port: 8090
spring:
  #配置数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://124.221.248.30:3306/stx-pro-three?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    username: stx-pro-three
    password: root
    #  配置redis
  redis:
    #    数据库名称
    database: 15
    #    数据库地址
    host: 124.221.248.30
    #    数据库端口号
    port: 6379
    #    配置文件
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    #    redis密码
    password: dwadwa#dawd233
  #    缓存的机制
  cache:
    type: redis
  thymeleaf:
    excluded-view-names:
#mybatis-plus配置文件
mybatis-plus:
  configuration:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
    #    日志文件
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true
  #    配置Mybatis配置文件位置
  mapper-locations: classpath*:/mybatis/mapper/*.xml
jackson:
  date-format: yyyy-MM-dd
  time-zone: GMT+8
